CREATE VIEW VW_DETAYLI_ODEME
AS
SELECT "TRANSACTION_HEADER"."TRANS_DATE" 'TARİH',
       "USERS"."CODE" 'KOD',
       CASE "TRANSACTION_PAYMENT"."PAYMENT_TYPE"
           WHEN 1 THEN
               -TRANSACTION_PAYMENT.PAYMENT_TOTAL
           WHEN 0 THEN
               TRANSACTION_PAYMENT.PAYMENT_TOTAL
       END 'ALINAN ÖDEME',
       "PAYMENT_TYPE"."DESCRIPTION" 'ÖDEME TİPİ',
       CASE "TRANSACTION_PAYMENT"."PAYMENT_TYPE"
           WHEN 1 THEN
               'PARA ÜSTÜ'
           WHEN 0 THEN
               'ÖDEME'
       END 'İŞLEM',
       CASE TRANSACTION_HEADER.PTYPE
           WHEN 0 THEN
               'SATIŞ'
           WHEN 1 THEN
               'SATIŞ'
           WHEN 2 THEN
               'İADE'
       END 'İŞLEM TİPİ',
       "POS"."DESCRIPTION" 'YAZAR KASA',
       "TRANSACTION_HEADER"."CUSTOMER_CODE" 'MÜŞTERİ KART NUMARASI',
       "TRANSACTION_HEADER"."RECEIPT_BARCODE" 'BELGE BARKODU'
FROM(((((TRANSACTION_PAYMENT TRANSACTION_PAYMENT
    INNER JOIN TRANSACTION_HEADER TRANSACTION_HEADER
        ON TRANSACTION_PAYMENT."FK_TRANSACTION_HEADER" = TRANSACTION_HEADER."ID")
    INNER JOIN PAYMENT_TYPE PAYMENT_TYPE
        ON TRANSACTION_PAYMENT."FK_PAYMENT_TYPE" = PAYMENT_TYPE."ID")
    INNER JOIN USERS USERS
        ON TRANSACTION_HEADER."FK_USER" = USERS."ID")
    INNER JOIN POS POS
        ON TRANSACTION_HEADER."FK_POS" = POS."ID")
    INNER JOIN DOCUMENT DOCUMENT
        ON TRANSACTION_HEADER."PTYPE" = DOCUMENT."NUM")
    INNER JOIN STORE STORE
        ON TRANSACTION_HEADER."FK_STORE" = STORE."ID"
WHERE TRANSACTION_HEADER."STATUS" = 0
      AND DOCUMENT."PRICE_FLAG" <> 0
      AND TRANSACTION_HEADER."ID" NOT IN
          (
              SELECT TRANSACTION_HEADER."FK_TRANSACTION_HEADER"
              FROM TRANSACTION_HEADER
              WHERE TRANSACTION_HEADER."PTYPE" = 20
          )
      AND TRANSACTION_HEADER."PTYPE" <> 20;
